/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaryd_net_RTPManager */

#ifndef _Included_com_jaryd_net_RTPManager
#define _Included_com_jaryd_net_RTPManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaryd_net_RTPManager
 * Method:    _init
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_jaryd_net_RTPManager__1init
  (JNIEnv *, jobject);

/*
 * Class:     com_jaryd_net_RTPManager
 * Method:    _send
 * Signature: (J[BILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jaryd_net_RTPManager__1sendH264
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jstring, jint);

JNIEXPORT void JNICALL Java_com_jaryd_net_RTPManager__1sendOgg
        (JNIEnv *, jobject, jlong, jbyteArray, jint, jstring, jint);

/*
 * Class:     com_jaryd_net_RTPManager
 * Method:    _listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jaryd_net_RTPManager__1listen
  (JNIEnv *, jobject, jlong,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
