/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaryd_voiphone_audio_AudioProcessor */

#ifndef _Included_com_jaryd_voiphone_audio_AudioProcessor
#define _Included_com_jaryd_voiphone_audio_AudioProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaryd_voiphone_audio_AudioProcessor
 * Method:    _init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_jaryd_voiphone_audio_AudioProcessor__1init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_jaryd_voiphone_audio_AudioProcessor
 * Method:    _process
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_jaryd_voiphone_audio_AudioProcessor__1process
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     com_jaryd_voiphone_audio_AudioProcessor
 * Method:    _putPlayback
 * Signature: (J[S)V
 */
JNIEXPORT void JNICALL Java_com_jaryd_voiphone_audio_AudioProcessor__1putPlayback
  (JNIEnv *, jobject, jlong, jshortArray);

/*
 * Class:     com_jaryd_voiphone_audio_AudioProcessor
 * Method:    _cancle
 * Signature: (J[SI[S)V
 */
JNIEXPORT void JNICALL Java_com_jaryd_voiphone_audio_AudioProcessor__1cancle
  (JNIEnv *, jobject, jlong, jshortArray, jint, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
